### ISSUE TITLE
Feature request: Search snippets by their description

### ISSUE THREAD

**Issue by ajitid** [fhill2/telescope-ultisnips.nvim#3]
Searching snippets by their description is useful, for example, to get a list of all "hooks" of React library. `honza/vim-snippets` uses the word hook in each of hook snippet's description. This could be also useful when we are expecting for a snippet to exist and are searching for it by typing words that can occur in its description.

**Comment by ajitid** [comment]
Looks like [converting `ordinal` assignment](https://github.com/fhill2/telescope-ultisnips.nvim/blob/ddef432a8dbd6d48ead5a63fe8515ba0e5c12021/lua/telescope/_extensions/ultisnips.lua#L70) to `ordinal = entry.name  .. ' ' .. entry.desc` works just fine. (This is with nvim-telescope/telescope-fzf-native.nvim installed.) However I haven't worked with Telescope before so having a proper solution would be appreciated.

**Comment by fhill2** [comment]
@zlksnk Thank you for notifying me about this! 
ordinal is now set to `entry.filename .. ' ' .. entry.name .. ' ' .. entry.desc` so all category/name/description are all searchable.
Let me know if this behaviour has been corrected for you.

**Comment by ajitid** [comment]
Thanks for changing it! My initial thought was not to include filename there as it is mostly never be the case that I would be searching using filename field. I still won't be doing that, but given we devs work with many libraries we can split snippets suffixed with with lib name which can help in narrowing down the search even if description is not available. 👍

Edit: Filename = Category, like you said in your comment. :)

![image](https://user-images.githubusercontent.com/26769888/117561962-16b89580-b050-11eb-9eb3-c3ea69e7da94.png)
